spring.application.name=projeto-cadastro-usuarios
server.port=5050
# configurações H2 database

# habilita a interface web do H2
spring.h2.console.enabled=true
# definindo o endereço da interface web do H2
spring.h2.console.path=/h2-console
# definindo a url do banco de dados
spring.datasource.url=jdbc:h2:mem:testdb
# informa qual driver java será usado para acessar o banco de dados
spring.datasource.driver-class-name=org.h2.Driver
# definindo usuário do banco de dados
spring.datasource.username=marcos
# definindo senha do banco de dados
spring.datasource.password=12345678
